%Cria a estrutura de dados que contem as informacoes de atitude e posicao
%do corpo.

function pose = pose_create;

pose = struct('x',0,'y',0,'z',0,...
   'dx_dt',0,'dy_dt',0,'dz_dt',0,...
   'd2x_dt2',0,'d2y_dt2',0,'d2z_dt2',0,...
   'pitch',0,'yaw',0,'roll',0,...
   'q0',0,'q1',0,'q2',0,'q3',0,...
   'xvariance',0,'yvariance',0,'zvariance',0,...
   'dx_dtvariance',0,'dy_dtvariance',0,'dz_dtvariance',0,...
   'pitchvariance',0,'yawvariance',0,'rollvariance',0,...
   'q0variance',0,'q1variance',0,'q2variance',0,'q3variance',0);
